In [22]:
import pandapower as pp
net=pp.create_empty_network()

In [23]:
bus1=pp.create_bus(net, name="HV Busbar", vn_kv=22.011, type="n")
bus2=pp.create_bus(net, name="HV Busbar 2",vn_kv=2.992, type="n")
bus3 = pp.create_bus(net, name="HV Transformer Bus", vn_kv=207.68, type="b")
bus4 = pp.create_bus(net, name="MV Transformer Bus", vn_kv=209.88, type="b")
bus5 = pp.create_bus(net, name="MV Main Bus", vn_kv=111.1, type="b")
bus6 = pp.create_bus(net, name="MV Bus 1", vn_kv=99, type="b")

In [24]:
net.bus

                 name    vn_kv type  zone  in_service
0           HV Busbar   22.011    n  None        True
1         HV Busbar 2    2.992    n  None        True
2  HV Transformer Bus  207.680    b  None        True
3  MV Transformer Bus  209.880    b  None        True
4         MV Main Bus  111.100    b  None        True
5            MV Bus 1   99.000    b  None        True

In [25]:
trafo1=pp.create_transformer(net, bus3, bus1, name="T1",  std_type="63 MVA 110/20 kV")
trafo2=pp.create_transformer(net, bus4, bus2, name="T2", std_type="40 MVA 110/10 kV")
trafo3=pp.create_transformer(net, bus5, bus1, name="T3", std_type="40 MVA 110/20 kV")
trafo4=pp.create_transformer(net, bus6, bus2, name="T4", std_type="40 MVA 110/10 kV")

In [26]:
net.trafo

,name,std_type,hv_bus,lv_bus,sn_mva,vn_hv_kv,vn_lv_kv,vk_percent,vkr_percent,pfe_kw,...,tap_neutral,tap_min,tap_max,tap_step_percent,tap_step_degree,tap_pos,tap_phase_shifter,parallel,df,in_service
0,T1,63 MVA 110/20 kV,2,0,63.0,110.0,20.0,18.0,0.32,22.0,...,0,-9,9,1.5,0.0,0,False,1,1.0,True
1,T2,40 MVA 110/10 kV,3,1,40.0,110.0,10.0,16.2,0.34,18.0,...,0,-9,9,1.5,0.0,0,False,1,1.0,True
2,T3,40 MVA 110/20 kV,4,0,40.0,110.0,20.0,16.2,0.34,18.0,...,0,-9,9,1.5,0.0,0,False,1,1.0,True
3,T4,40 MVA 110/10 kV,5,1,40.0,110.0,10.0,16.2,0.34,18.0,...,0,-9,9,1.5,0.0,0,False,1,1.0,True

In [27]:
line1=pp.create_line(net, bus3, bus4, length_km=10, std_type="N2XS(FL)2Y 1x240 RM/35 64/110 kV",  name="Line1")
line2=pp.create_line(net, bus5, bus6, length_km=2.0, std_type="NA2XS2Y 1x240 RM/25 12/20 kV", name="Line2")

In [28]:
net.line

,name,std_type,from_bus,to_bus,length_km,r_ohm_per_km,x_ohm_per_km,c_nf_per_km,g_us_per_km,max_i_ka,df,parallel,type,in_service
0,Line1,N2XS(FL)2Y 1x240 RM/35 64/110 kV,2,3,10.0,0.075,0.149,135.0,0.0,0.526,1.0,1,cs,True
1,Line2,NA2XS2Y 1x240 RM/25 12/20 kV,4,5,2.0,0.122,0.112,304.0,0.0,0.421,1.0,1,cs,True

In [29]:
pp.create_gen(net, bus1, p_mw=54, sn_mva=90, vn_kv=22, name="generator")
net.gen

,name,bus,p_mw,q_mvar,sn_mva,scaling,in_service,type,current_source,vn_kv
0,generator,0,54.0,0.0,90.0,1.0,True,wye,True,22.0

In [32]:
pp.create_load_from_cosphi(net, bus2, sn_mva=57, cos_phi=0.6, mode="underexcited", name="load")
net.load

,name,bus,p_mw,q_mvar,const_z_percent,const_i_percent,sn_mva,scaling,in_service,type
0,load,1,34.2,0.0,0.0,0.0,57.0,1.0,True,wye
1,load,1,34.2,45.6,0.0,0.0,57.0,1.0,True,wye

In [ ]:
pp.create_ext_grid(net, bus1, vm_pu=1, va_degree=50)
net.ext_grid

In [31]:
pp.runpp(net)
net.res_bus
net.res_trafo
net.res_line
net.res_sgen
net.res_load

d:\anaconda3\lib\site-packages\pandapower\auxiliary.py:1028: RuntimeWarning: invalid value encountered in double_scalars
  init_vm_pu = (net.ext_grid.vm_pu.values.sum() + net.gen.vm_pu.values.sum()) / \

UserWarning: No reference bus is available. Either add an ext_grid or a gen with slack=True